apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: logs-dir
          persistentVolumeClaim:
            claimName: log-output-claim
        - name: config
          configMap:
            name: log-config-map
            items:
            - key: "information.txt"
              path: "information.txt"
      containers:
        - name: log-writer
          image: benpp/log-writer:1.10
          volumeMounts:
            - name: logs-dir
              mountPath: /app/logs
        - name: log-server
          image: benpp/log-server:2.5
          env:
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:2345"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config-map
                  key: message
          volumeMounts:
            - name: logs-dir
              mountPath: /app/logs
            - name: config
              mountPath: /app/data
              readOnly: true
