apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
  namespace: exercises
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 2m
    successCondition: result  < 50.0
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1769-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m]))*100
