apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-todo-job
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-todo
            image: benpp/create-todo:2.9
            imagePullPolicy: Always
            env:
              - name: TODO_URL
                value: "http://todo-backend-svc:2345"
          restartPolicy: OnFailure
