apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ivhY5vbIzQOZ72sfCH7zjKYx8xBvC3idXfr8cA==,iv:fKdfH/ueMvCeohSf3jhTgOnAPw17/oa2yiC1zEHqW6I=,tag:TM2g8NFROuB1dCBGwqmu1g==,type:str]
sops:
    age:
        - recipient: age1jklf304f3qhsg9jlwelvk0zvm9nhymvytrlr96tms6nt6ns8j3ms47mzc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VThFUGluc08rVlVpSytJ
            TWprU0dJNlVWQ2Q2QUQ5SFNDcXQvaXIyenlFCmtsMUpxZ1haa05iZSsyYmo0cWVS
            UlBDL1VRdi9aZEUrVFFUaWdHbjlJNEUKLS0tIEh1M1QzVkNHbFdJV01WRFpzcW5z
            b01aVkNFRjNtS2NvRUZGbDYwdnJ1VzgKfay1b/vdPCxggrRyLgBTTc0NQ8wdq/Qa
            +TpWTrNZVQTNyxEp1eBE8eusibgTH2yGBFDwwtFP10I+6i28oesUgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T17:38:27Z"
    mac: ENC[AES256_GCM,data:MqZSIp4uDP7hxRHBdp7ieW2/OO2U3J2zCKL3d4ynBvecp4uF6WDKV9GjMpU79brDkP1IMs6yXu5TAVVMW6u6Iv2fe8UnzHssBf7/zSHoan4dDjWKok9iYMMWOv9DnOCwbGkW1jM1WIGYQsoQ9lWNJMto1g0C+vQjR08RBo2WMQI=,iv:tfWtE+negPecPk3LWzdBXNn4eAz4VUDH4qoKuHV37JI=,tag:3QAMmzurE70iC/yMm0mmiA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
